### ISSUE TITLE
Golang-CI lint notice for disabling thelper for library lines

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/gherkingen#53]
```
issues:
  fix: true
  exclude-rules:
    - linters:
        - thelper
      source: "^.*f\\.Scenario.*$"
```
